version 3.0.0
uploadcare/uploadcare-rails pull request #112
Opened 2022-10-02 08:30 UTC by T0mbery

## Description

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2022-10-03 17:41 UTC, rsedykh requested changes

2022-10-03 17:41 UTC, rsedykh commented on CHANGELOG.md
> +  - Field `appdata` that includes dictionary of application names and data associated with these applications
Looks like these are added, not changed.

2022-10-03 17:41 UTC, rsedykh commented on CHANGELOG.md
> +  - Remove the option of sorting the file list by file size
```suggestion
  - Removed the option of sorting the file list by file size
```

2022-10-03 17:41 UTC, rsedykh commented on CHANGELOG.md
> + - Change response format
```suggestion
 - Changed response format
```

2022-10-03 17:41 UTC, rsedykh commented on CHANGELOG.md
> +- Added a possibility to delete a Group
```suggestion
- Added an option to delete a Group
```

2022-10-03 17:41 UTC, rsedykh commented on README.md
> +#### Delete a file group by its ID.
```suggestion
#### Delete a file group by its ID
```

2022-10-03 17:41 UTC, rsedykh commented on README.md
> +#### Update the value of a single metadata key. If the key does not exist, it will be created
```suggestion
#### Update the value of a single metadata key

If the key does not exist, it will be created.
```

2022-10-03 17:41 UTC, rsedykh commented on README.md
> +#### Execute AWS Rekognition Add-On for a given target to detect labels in an image.
```suggestion
#### Execute AWS Rekognition Add-On for a given target to detect labels in an image
```

2022-10-03 17:41 UTC, rsedykh commented on README.md
> +#### Check the status of an Add-On execution request that had been started using the Execute Add-On operation.
```suggestion
#### Check the status of an Add-On execution request that had been started using the Execute Add-On operation
```

2022-10-03 17:41 UTC, rsedykh commented on README.md
> +#### Execute ClamAV virus checking Add-On for a given target.
```suggestion
#### Execute ClamAV virus checking Add-On for a given target
```

2022-10-03 17:41 UTC, rsedykh commented on README.md
> +#### Check the status of an Add-On execution request that had been started using the Execute Add-On operation.
```suggestion
#### Check the status of an Add-On execution request that had been started using the Execute Add-On operation
```

2022-10-03 17:41 UTC, rsedykh commented on README.md
> +#### Execute remove.bg background image removal Add-On for a given target.
```suggestion
#### Execute remove.bg background image removal Add-On for a given target
```

2022-10-03 17:41 UTC, rsedykh commented on README.md
> +#### Check the status of an Add-On execution request that had been started using the Execute Add-On operation.
```suggestion
#### Check the status of an Add-On execution request that had been started using the Execute Add-On operation
```

2022-10-04 09:17 UTC, dmitrijivanchenko approved these changes

2022-10-10 18:29 UTC, T0mbery commented on CHANGELOG.md
> +  - Field `appdata` that includes dictionary of application names and data associated with these applications
это не совсем добавление, это скорее изменение ответа эндпоинта get_file

2022-10-13 17:31 UTC, rsedykh requested changes
Please apply the same changes to changelog that you'll apply to uploadcare-ruby

2022-10-13 17:38 UTC, rsedykh commented
Please also search for all mentions of v0.6.0 and change it to v0.7.0 where it's necessary.
Maybe you should change `application/vnd.uploadcare-v0.6+json` to `application/vnd.uploadcare-v0.7+json` too.
Same about 0.5.0.

And tests are failing. :-(

2022-12-13 16:10 UTC, rsedykh approved these changes

2022-12-25 12:10 UTC, merged